### PR TITLE
docs: 更新使用文档 #59

### PR DESCRIPTION
**Pull request by Jackvideo**
1. Cython版本已经不支持PyYAML 6.0了，改成PyYAML==6.0.1可以解决
2. Resource的README.md中，返回多条数据应声明many_response_data=True而非many_response=True

### CODE REVIEW

**Comment by tencentblueking-adm** [comment]
[CLA assistant check](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-resource?pullRequest=58) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-resource?pullRequest=58) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-resource?pullRequest=58) it.</sub>

**Comment by OrenZhang** [comment]
Commit Message 不规范，请修改为 `docs: 更新使用文档 #59`

**Comment by Jackvideo** [comment]
> Commit Message 不规范，请修改为 `docs: 更新使用文档 #59`

已修改

**Comment by Jackvideo** [comment]
> Commit Message 不规范，请修改为 `docs: 更新使用文档 #59`
已修改！

**Comment by OrenZhang** [comment]
> > Commit Message 不规范，请修改为 `docs: 更新使用文档 #59`
> > 已修改！

目前看仍然是没有生效的～

image

**Pull request closed without merging**
